[package]
name = "koa-infer"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[features]
cuda = []

[dependencies]
anyhow.workspace = true
memmap2.workspace = true
safetensors.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokenizers.workspace = true
toml.workspace = true

[dev-dependencies]
tempfile.workspace = true
